// src/lib/components/widgets/FinanceWidget.svelte
<script>
  import WidgetContainer from '../WidgetContainer.svelte';
  import { finance } from '../../../stores/appStores.js';
  import { Plus, Minus, ArrowUpRight, ArrowDownRight } from 'lucide-svelte';
  import { v4 as uuidv4 } from 'uuid';
  import { Archive } from 'lucide-svelte';

  export let title;
  export let startDrag;

  let amount = '';
  let type = 'expense'; // 'income' | 'expense'

  function addTransaction() {
    if (!amount || isNaN(amount)) return;
    
    const val = parseFloat(amount);
    const newTransaction = {
      id: uuidv4(),
      type,
      amount: val,
      date: new Date().toISOString()
    };

    finance.update(store => {
      const newBalance = type === 'income' ? store.balance + val : store.balance - val;
      return {
        balance: newBalance,
        transactions: [newTransaction, ...store.transactions].slice(0, 10) // Keep last 10
      };
    });

    amount = '';
  }
</script>

<WidgetContainer {title} headerAction={Plus} {startDrag}>
  <div class="flex flex-col h-full">
    <div class="mb-4">
      <h4 class="text-xs md:text-sm text-gray-500 font-medium uppercase tracking-wider">Total Balance</h4>
      <p class="text-2xl md:text-4xl font-bold text-apple-dark tracking-tight">${$finance.balance.toFixed(2)}</p>
    </div>

    <!-- Quick Add -->
    <div class="flex gap-2 mb-4">
      <input 
        type="number" 
        bind:value={amount}
        placeholder="0.00" 
        class="w-full bg-white/50 border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50"
      />
      <div class="flex bg-gray-100 p-1 rounded-lg">
        <button 
          class="p-1 rounded-md transition-colors {type === 'income' ? 'bg-white shadow-sm text-green-600' : 'text-gray-400'}"
          onclick={() => type = 'income'}
        >
          <Plus size={16} />
        </button>
        <button 
          class="p-1 rounded-md transition-colors {type === 'expense' ? 'bg-white shadow-sm text-red-600' : 'text-gray-400'}"
          onclick={() => type = 'expense'}
        >
          <Minus size={16} />
        </button>
      </div>
      <button 
        class="bg-blue-500 text-white px-3 py-1 rounded-lg text-sm font-medium hover:bg-blue-600 transition-colors"
        onclick={addTransaction}
      >
        Add
      </button>
    </div>

    <!-- Recent Transactions -->
    <div class="flex-1 overflow-y-auto no-scrollbar space-y-2">
      {#if $finance.transactions.length > 0}
        {#each $finance.transactions as t (t.id)}
          <div class="flex justify-between items-center p-2 rounded-lg bg-white/40 hover:bg-white/60 transition-colors">
            <div class="flex items-center gap-2">
              <div class="p-1 rounded-full {t.type === 'income' ? 'bg-green-100 text-green-600' : 'bg-red-100 text-red-600'}">
                {#if t.type === 'income'}
                  <ArrowUpRight size={14} />
                {:else}
                  <ArrowDownRight size={14} />
                {/if}
              </div>
              <span class="text-sm text-gray-700 capitalize">{t.type}</span>
            </div>
            <span class="text-sm font-semibold {t.type === 'income' ? 'text-green-600' : 'text-red-600'}">
              {t.type === 'income' ? '+' : '-'}${t.amount.toFixed(2)}
            </span>
          </div>
        {/each}
      {:else}
        <div class="h-full flex flex-col items-center justify-center text-gray-400 gap-2 min-h-[100px]">
           <Archive size={24} class="opacity-50" />
           <p class="text-xs">No transactions yet</p>
        </div>
      {/if}
    </div>
  </div>
</WidgetContainer>

// src/components/FinanceWidget.tsx
import React, { useState } from 'react';
import { ComicCard, ComicButton, ComicInput } from './ui/ComicCard';
import { DollarSign, TrendingUp, TrendingDown, Plus, Save, Edit2 } from 'lucide-react';
import { PieChart, Pie, Cell, ResponsiveContainer } from 'recharts';
import { Transaction } from '../types';

interface FinanceWidgetProps {
  transactions: Transaction[];
  onAddTransaction: (t: Transaction) => void;
  onEditTransaction: (t: Transaction) => void;
  onDeleteTransaction: (id: string) => void;
  savings: { target: number; current: number; name: string };
  onUpdateSavings: (val: number) => void;
}

const COLORS = ['#86efac', '#fca5a5']; // Green (Income), Red (Expense)

export const FinanceWidget: React.FC<FinanceWidgetProps> = ({ transactions, onAddTransaction, onEditTransaction, onDeleteTransaction, savings, onUpdateSavings }) => {
  const [amount, setAmount] = useState('');
  const [desc, setDesc] = useState('');
  const [type, setType] = useState<'income' | 'expense'>('expense');
  const [editingId, setEditingId] = useState<string | null>(null);

  const handleSubmit = () => {
    if (!amount || !desc) return;
    
    const transactionData = {
      id: editingId || Date.now().toString(),
      amount: parseFloat(amount),
      description: desc,
      type,
      date: editingId ? transactions.find(t => t.id === editingId)?.date || new Date().toISOString() : new Date().toISOString()
    };

    if (editingId) {
        onEditTransaction(transactionData);
        setEditingId(null);
    } else {
        onAddTransaction(transactionData);
    }
    
    setAmount('');
    setDesc('');
    setType('expense');
  };

  const handleEditClick = (t: Transaction) => {
    setEditingId(t.id);
    setAmount(t.amount.toString());
    setDesc(t.description);
    setType(t.type);
  };

  const handleCancelEdit = () => {
    setEditingId(null);
    setAmount('');
    setDesc('');
    setType('expense');
  };

  const totalIncome = transactions.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
  const totalExpense = transactions.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0);
  const balance = totalIncome - totalExpense;

  const chartData = [
    { name: 'Income', value: totalIncome },
    { name: 'Expense', value: totalExpense },
  ];

  return (
    <ComicCard title="Finance" color="green" icon={<DollarSign className="w-5 h-5" />}>
      <div className="flex flex-col h-full gap-4">
        
        {/* Balance Card */}
        <div className="bg-emerald-50 border-2 border-black rounded-lg p-3 flex justify-between items-center shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
          <div>
            <p className="text-xs font-bold uppercase text-emerald-900">Net Balance</p>
            <p className="text-2xl font-black text-black">${balance.toFixed(2)}</p>
          </div>
          <div className="h-12 w-12">
             <ResponsiveContainer width="100%" height="100%">
               <PieChart>
                 <Pie data={chartData} cx="50%" cy="50%" innerRadius={10} outerRadius={20} fill="#8884d8" paddingAngle={5} dataKey="value">
                   {chartData.map((entry, index) => (
                     <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} stroke="black" strokeWidth={1} />
                   ))}
                 </Pie>
               </PieChart>
             </ResponsiveContainer>
          </div>
        </div>

        {/* Savings Goal */}
        <div className="space-y-1">
            <div className="flex justify-between text-sm font-bold text-black">
                <span>{savings.name}</span>
                <span>${savings.current} / ${savings.target}</span>
            </div>
            <div className="h-4 w-full bg-white border-2 border-black rounded-full overflow-hidden relative">
                <div 
                    className="h-full bg-yellow-300 border-r-2 border-black transition-all duration-500"
                    style={{ width: `${Math.min((savings.current / savings.target) * 100, 100)}%` }}
                />
            </div>
            <div className="flex gap-2 mt-1">
                <button onClick={() => onUpdateSavings(savings.current + 10)} className="text-xs font-bold underline text-emerald-800 hover:text-emerald-950">+$10</button>
                <button onClick={() => onUpdateSavings(savings.current + 50)} className="text-xs font-bold underline text-emerald-800 hover:text-emerald-950">+$50</button>
            </div>
        </div>

        {/* Input Area */}
        <div className={`flex flex-col gap-2 p-2 rounded-lg border-2 border-dashed transition-colors ${editingId ? 'bg-yellow-50 border-yellow-400' : 'bg-gray-50 border-gray-300'}`}>
          {editingId && <p className="text-xs font-black text-yellow-800 uppercase">Editing Transaction</p>}
          <div className="flex gap-2">
             <ComicInput 
                placeholder="$0.00" 
                type="number" 
                value={amount} 
                onChange={(e) => setAmount(e.target.value)}
                className="w-1/3"
             />
             <ComicInput 
                placeholder="Coffee, Salary..." 
                value={desc} 
                onChange={(e) => setDesc(e.target.value)}
                className="w-2/3"
             />
          </div>
          <div className="flex gap-2">
            <button 
                onClick={() => setType('income')}
                className={`flex-1 py-1 rounded border-2 border-black text-xs font-bold transition-colors ${type === 'income' ? 'bg-emerald-300 text-black' : 'bg-white text-gray-700'}`}
            >
                Income
            </button>
            <button 
                onClick={() => setType('expense')}
                className={`flex-1 py-1 rounded border-2 border-black text-xs font-bold transition-colors ${type === 'expense' ? 'bg-red-300 text-black' : 'bg-white text-gray-700'}`}
            >
                Expense
            </button>
            <ComicButton onClick={handleSubmit} className="bg-black text-white min-w-[60px] flex justify-center">
                {editingId ? <Save className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
            </ComicButton>
            {editingId && (
                <ComicButton onClick={handleCancelEdit} variant="danger" className="min-w-[40px] flex justify-center">
                    x
                </ComicButton>
            )}
          </div>
        </div>

        {/* List */}
        <div className="flex-1 overflow-auto space-y-2 max-h-40">
            {transactions.slice().reverse().map(t => (
                <div key={t.id} className={`flex justify-between items-center p-2 bg-white border-2 border-black rounded shadow-[2px_2px_0px_0px_rgba(0,0,0,0.2)] ${editingId === t.id ? 'ring-2 ring-yellow-400' : ''}`}>
                    <div className="flex items-center gap-2">
                        {t.type === 'income' ? <TrendingUp className="w-4 h-4 text-emerald-700"/> : <TrendingDown className="w-4 h-4 text-red-600"/>}
                        <span className="text-sm font-bold text-gray-900 truncate w-20 sm:w-24">{t.description}</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <span className={`font-black ${t.type === 'income' ? 'text-emerald-700' : 'text-red-600'}`}>
                            {t.type === 'income' ? '+' : '-'}${t.amount}
                        </span>
                        <button onClick={() => handleEditClick(t)} className="text-gray-400 hover:text-blue-600 px-1">
                            <Edit2 className="w-3 h-3" />
                        </button>
                        <button onClick={() => onDeleteTransaction(t.id)} className="text-gray-400 hover:text-red-600 font-bold px-1">×</button>
                    </div>
                </div>
            ))}
            {transactions.length === 0 && <p className="text-center text-gray-500 text-sm italic font-medium">No transactions yet.</p>}
        </div>

      </div>
    </ComicCard>
  );
};
