// src/lib/components/widgets/PomodoroWidget.svelte
<script>
  import WidgetContainer from '../WidgetContainer.svelte';
  import { Play, Pause, RotateCcw } from 'lucide-svelte';
  import { onDestroy } from 'svelte';

  export let title;

  let timeLeft = 25 * 60; // 25 minutes
  let isRunning = false;
  let timerId = null;
  let mode = 'focus'; // 'focus' | 'break'

  function formatTime(seconds) {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  }

  function toggleTimer() {
    if (isRunning) {
      clearInterval(timerId);
    } else {
      timerId = setInterval(() => {
        if (timeLeft > 0) {
          timeLeft--;
        } else {
          clearInterval(timerId);
          isRunning = false;
          // Play sound or notify
        }
      }, 1000);
    }
    isRunning = !isRunning;
  }

  function resetTimer() {
    clearInterval(timerId);
    isRunning = false;
    timeLeft = mode === 'focus' ? 25 * 60 : 5 * 60;
  }

  function setMode(newMode) {
    mode = newMode;
    resetTimer();
  }

  onDestroy(() => {
    if (timerId) clearInterval(timerId);
  });
</script>

<WidgetContainer {title}>
  <div class="flex flex-col h-full items-center justify-center relative">
    <!-- Mode Switcher -->
    <div class="absolute top-0 left-0 right-0 flex justify-center gap-2 mb-4">
      <button 
        class="text-xs px-3 py-1 rounded-full transition-colors {mode === 'focus' ? 'bg-blue-100 text-blue-600 font-medium' : 'text-gray-400 hover:bg-gray-100'}"
        onclick={() => setMode('focus')}
      >
        Focus
      </button>
      <button 
        class="text-xs px-3 py-1 rounded-full transition-colors {mode === 'break' ? 'bg-green-100 text-green-600 font-medium' : 'text-gray-400 hover:bg-gray-100'}"
        onclick={() => setMode('break')}
      >
        Break
      </button>
    </div>

    <!-- Timer Display -->
    <div class="text-6xl font-light text-apple-dark tabular-nums tracking-tighter mb-8 mt-6">
      {formatTime(timeLeft)}
    </div>

    <!-- Controls -->
    <div class="flex items-center gap-4">
      <button 
        class="w-12 h-12 rounded-full flex items-center justify-center transition-all hover:scale-105 active:scale-95
        {isRunning ? 'bg-amber-100 text-amber-600' : 'bg-blue-500 text-white shadow-lg shadow-blue-200'}"
        onclick={toggleTimer}
      >
        {#if isRunning}
          <Pause size={20} fill="currentColor" />
        {:else}
          <Play size={20} fill="currentColor" class="ml-1" />
        {/if}
      </button>

      <button 
        class="w-10 h-10 rounded-full bg-gray-100 text-gray-500 flex items-center justify-center hover:bg-gray-200 transition-colors"
        onclick={resetTimer}
      >
        <RotateCcw size={16} />
      </button>
    </div>
  </div>
</WidgetContainer>

// src/components/PomodoroWidget.tsx
import React, { useState, useEffect, useRef } from 'react';
import { ComicCard, ComicButton } from './ui/ComicCard';
import { Timer, Play, Pause, RotateCcw } from 'lucide-react';

export const PomodoroWidget: React.FC = () => {
  const [timeLeft, setTimeLeft] = useState(25 * 60);
  const [isActive, setIsActive] = useState(false);
  const [mode, setMode] = useState<'work' | 'short' | 'long'>('work');
  const intervalRef = useRef<number | null>(null);

  useEffect(() => {
    if (isActive) {
      intervalRef.current = window.setInterval(() => {
        setTimeLeft((time) => {
          if (time <= 1) {
            setIsActive(false);
            return 0;
          }
          return time - 1;
        });
      }, 1000);
    } else if (intervalRef.current) {
      clearInterval(intervalRef.current);
    }
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, [isActive]);

  const toggleTimer = () => setIsActive(!isActive);
  
  const resetTimer = () => {
    setIsActive(false);
    if (mode === 'work') setTimeLeft(25 * 60);
    if (mode === 'short') setTimeLeft(5 * 60);
    if (mode === 'long') setTimeLeft(15 * 60);
  };

  const changeMode = (m: 'work' | 'short' | 'long') => {
    setMode(m);
    setIsActive(false);
    if (m === 'work') setTimeLeft(25 * 60);
    if (m === 'short') setTimeLeft(5 * 60);
    if (m === 'long') setTimeLeft(15 * 60);
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const progress = 1 - (timeLeft / (mode === 'work' ? 25*60 : mode === 'short' ? 5*60 : 15*60));

  return (
    <ComicCard title="Focus" color="orange" icon={<Timer className="w-5 h-5" />}>
      <div className="flex flex-col items-center justify-center h-full gap-4 relative">
        
        <div className="flex w-full mb-2 border-2 border-black rounded-lg overflow-hidden shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] bg-white">
            {(['work', 'short', 'long'] as const).map((m, idx, arr) => (
                <button
                    key={m}
                    onClick={() => changeMode(m)}
                    className={`flex-1 text-xs font-black py-2 transition-colors hover:bg-orange-100 ${mode === m ? 'bg-orange-400 text-black' : 'bg-transparent text-gray-500'} ${idx !== arr.length - 1 ? 'border-r-2 border-black' : ''}`}
                >
                    {m === 'work' ? 'Work' : m === 'short' ? 'Break' : 'Long'}
                </button>
            ))}
        </div>

        <div className="relative w-40 h-40 flex items-center justify-center bg-orange-50 rounded-full border-4 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
             {/* Progress Ring Simulation */}
            <svg className="absolute top-0 left-0 w-full h-full transform -rotate-90 pointer-events-none">
                <circle cx="50%" cy="50%" r="45%" fill="transparent" strokeWidth="8" stroke="rgba(0,0,0,0.1)" />
                <circle 
                    cx="50%" cy="50%" r="45%" 
                    fill="transparent" 
                    strokeWidth="8" 
                    stroke="#f97316" /* orange-500 */
                    strokeDasharray={`${2 * Math.PI * 70}`}
                    strokeDashoffset={`${2 * Math.PI * 70 * (1 - progress)}`}
                    strokeLinecap="round"
                    className="transition-all duration-1000"
                    style={{ r: '45%' }} // Explicit radius for simple SVG calc
                />
            </svg>
            <span className="text-4xl font-black tabular-nums relative z-10 text-black">{formatTime(timeLeft)}</span>
        </div>

        <div className="flex gap-4 w-full mt-2">
            <ComicButton onClick={toggleTimer} className="flex-1 flex justify-center items-center gap-2 h-12 text-lg">
                {isActive ? <Pause className="w-5 h-5 fill-current" /> : <Play className="w-5 h-5 fill-current" />} 
                {isActive ? 'Pause' : 'Start'}
            </ComicButton>
            <button onClick={resetTimer} className="w-12 h-12 flex items-center justify-center bg-white border-2 border-black rounded-lg shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] active:shadow-none active:translate-y-[2px] hover:bg-gray-50">
                <RotateCcw className="w-5 h-5 text-black" />
            </button>
        </div>
      </div>
    </ComicCard>
  );
};
